/**
 * Assembles the versioned scoring config + content data.
 *
 * SOURCE OF TRUTH: the five docs in the Blue Light Health "AI Quiz" Google Drive
 * folder (https://drive.google.com/drive/u/0/folders/1aouYdVqSbrQgGjASTnfruDSqvI-7kg-4).
 * Every value here derives from them — see config/source/SOURCES.md for the
 * file-by-file mapping, and SCORING.md for reconciliation decisions.
 *
 * Mechanical tables (tags, phenotype-meta, rule-weights, platforms,
 * subfeature-questions) are generated by scripts/generate-config.py from the
 * committed source sheets. Judgement tables (hook-job-map, gates, tie-breakers,
 * severity, params) are hand-authored. Nothing here reads prose — only ids.
 */

import type {
  Gate,
  Platform,
  PhenotypeProfile,
  QuizContent,
  RuleWeight,
  ScoringConfig,
  SeverityConfig,
  SubfeatureQuestion,
  TieBreakerPair,
} from "../types";
import type { HookTag, JobTag, PhenotypeId } from "../types";

import params from "./params.json";
import hookJobMap from "./hook-job-map.json";
import ruleWeights from "./rule-weights.json";
import gates from "./gates.json";
import tieBreakers from "./tie-breakers.json";
import severity from "./severity.json";
import tags from "./tags.json";
import phenotypeMeta from "./phenotype-meta.json";
import platforms from "./platforms.json";
import subfeatureQuestions from "./subfeature-questions.json";
import phenotypeLibrary from "./phenotypes.json";
import quizContent from "./quiz-content.json";

export interface TagDictEntry {
  type: string;
  tag: string;
  label: string;
}

export interface PhenotypeMeta {
  id: PhenotypeId;
  name: string;
  shortLabel: string;
}

export const TAGS = tags as TagDictEntry[];
export const PHENOTYPE_META = phenotypeMeta as PhenotypeMeta[];
export const PLATFORMS = platforms as Platform[];
export const SUBFEATURE_QUESTIONS = subfeatureQuestions as SubfeatureQuestion[];
export const PHENOTYPE_LIBRARY = phenotypeLibrary as unknown as PhenotypeProfile[];
export const QUIZ_CONTENT = quizContent as unknown as QuizContent;

/** Full phenotype profile by id (result copy + clinician metadata + AI corpus). */
export const PHENOTYPE_PROFILE = Object.fromEntries(
  PHENOTYPE_LIBRARY.map((p) => [p.id, p]),
) as Record<PhenotypeId, PhenotypeProfile>;

/** Sub-feature question lookup by `${platform}.${subfeature}`. */
export const SUBFEATURE_QUESTION_MAP = new Map(
  SUBFEATURE_QUESTIONS.map((q) => [`${q.platform}.${q.subfeature}`, q]),
);

/** Display name lookup, e.g. PHENOTYPE_NAME.night_regulator === "The Night Regulator". */
export const PHENOTYPE_NAME = Object.fromEntries(
  PHENOTYPE_META.map((p) => [p.id, p.name]),
) as Record<PhenotypeId, string>;

export const PHENOTYPE_SHORT_LABEL = Object.fromEntries(
  PHENOTYPE_META.map((p) => [p.id, p.shortLabel]),
) as Record<PhenotypeId, string>;

/** Human label for any tag, e.g. tagLabel("hook","zone_out") === "The Zone-Out". */
const TAG_LABEL = new Map<string, string>(
  TAGS.map((t) => [`${t.type}:${t.tag}`, t.label]),
);
export function tagLabel(type: string, tag: string): string {
  return TAG_LABEL.get(`${type}:${tag}`) ?? tag;
}

/** The fully assembled, versioned scoring config. */
export const scoringConfig: ScoringConfig = {
  version: params.version,
  anchorRankMultipliers: params.anchorRankMultipliers,
  hookJobMap: hookJobMap as Record<HookTag, JobTag[]>,
  ruleWeights: ruleWeights as RuleWeight[],
  gates: gates as Gate[],
  tieBreakers: tieBreakers as TieBreakerPair[],
  severity: severity as SeverityConfig,
  confidence: params.confidence,
  classification: params.classification as ScoringConfig["classification"],
};

export { params, platforms, subfeatureQuestions };
